### ISSUE TITLE
Can not be accessed in Docker

### ISSUE THREAD

**Issue by imakou** [ReactMaker/simple_react_start_kit_2017#36]
Hi,
The project cannot be accessed if it is running in Docker container
I ran the following commands:

`docker run -ti --name ReactKit -p 123:8000 -v "$PWD":/app node:6.3 bash`

When I was in the docker

`npm install` && `npm start`

I can even see the successful message like:
`webpack: Compiled successfully.`

But, I see the error on my Chrome as 
```
This site can’t be reached

The webpage at http://localhost:123/ might be temporarily down or it may have moved permanently to a new web address.
ERR_UNSAFE_PORT
```

Any idea?

Thank you so much.

**Comment by imakou** [comment]
I've solved this problem by changing 
`"start": "webpack-dev-server --env dev --colors --host 0.0.0.0",` in package.jon

TY

**Comment by chnbohwr** [comment]
I've add Dockerfile to this project and use nginx to serve website on #37 
see the README and enjoy it !!
